steps:
  #Validate source
  - task: Sam-Cogan.ARMTTKExtension.RunARMTTKTests.RunARMTTKTests@1
    displayName: 'Run Azure RM TTK Tests'
    inputs:
      templatelocation: '$(System.DefaultWorkingDirectory)\src\arm-templates'
      resultLocation: '$(Build.Repository.LocalPath)'
      cliOutputResults: true
  - task: PublishTestResults@2
    displayName: 'Publish - ARM Validation results'
    inputs:
      testResultsFormat: 'NUnit'
      failTaskOnFailedTests: true
      testResultsFiles: '$(Build.Repository.LocalPath)\*armttk.xml'
    condition: 'always()'

  #Create Artifact
  - task: CopyFiles@2
    displayName: "Copy - Script files to staging directory"
    inputs:
      SourceFolder: src\arm-templates
      TargetFolder: '$(Build.ArtifactStagingDirectory)\arm'

  #Publish Artifact
  - task: PublishBuildArtifacts@1
    displayName: "Publish - Artifacts"
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)"
      ArtifactName: "drop"
      publishLocation: "Container"
  - task: versioncounter@1
    displayName: "Update - Version number (develop)"
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    inputs:
      VersionVariable: "versionnumber"
      UpdateMinorVersion: false
      DevOpsPat: "$(devops-pipeline-pat)"
  - task: versioncounter@1
    displayName: "Update - Version number (Pull Request)"
    condition: and(succeeded(), and(eq(variables['Build.Reason'], 'PullRequest'), eq(variables['System.PullRequest.TargetBranch'], 'refs/heads/master')))
    inputs:
      VersionVariable: "versionnumber"
      UpdateMinorVersion: false
      OnlyUpdateMinor: true
      DevOpsPat: "$(devops-pipeline-pat)"